config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "subjects#index"
    resources :static_pages, only: %i(index)
    resources :subjects, only: %i(index) do
      resources :exams, only: %i(show create update index)
    end
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users

    resources :relationships, only: %i(create)

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages, only: %i(index)
      resources :users, only: %i(index)
      resources :users do
        resources :exams, only: %i(index show)
      end
      resources :account_activations, only: %i(update)
      resources :subjects, only: %i(index new create edit update destroy)
      resources  :subjects do
        resources :questions
      end
      resources :questions do
        collection {post :import}
      end
      resources :answers
    end
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  SUBJECT_ATTRS = %i(name description question_number duration
                                                      score_pass).freeze

  validates :name, :duration, :question_number, :score_pass, presence: true
  validates :name, uniqueness: {case_sensitive: false, message: :unique}
  validates :description, length: {maximum: Settings.description_max_length}
  validates :duration, :question_number, :score_pass,
            numericality: {only_integer: true}
  validate :check_score_pass, on: %i(create update)

  private
  def check_score_pass
    return unless score_pass.present? && question_number.present?
    return if score_pass <= question_number

    errors.add(:score_pass, :cannot_greater)
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::BaseController
  before_action :find_subject, except: %i(index new create)

  def index
    @search = Subject.ransack name_cont: params[:q] ? params[:q][:name] : ""
    @search.sorts = params.dig(:q, :s) || "id asc"
    @pagy, @subject_item = pagy @search.result, items: Settings.pagy
  end

  def new
    @subject = Subject.new
    return if @subject

    flash.now[:error] = t "not_found"
    redirect_to root_path
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t ".success_create"
      redirect_to admin_subjects_path
    else
      flash.now[:error] = t ".fail_create"
      render :new
    end
  end

  def edit; end

  def update
    if @subject.update subject_params
      flash[:success] = t ".update_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t ".update_false"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t ".subject_deleted"
    else
      flash[:danger] = t ".subject_delete_fail"
    end
    redirect_to admin_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit Subject::SUBJECT_ATTRS
  end

  def find_subject
    @subject = Subject.find_by id: params[:id]
    return if @subject.present?

    flash[:danger] = t "not_found"
    redirect_to admin_subjects_path
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    return unless user_signed_in?

    @search = Subject.ransack name_cont: params[:q] ? params[:q][:name] : ""
    @search.sorts = params.dig(:q, :s) || "id asc"
    @pagy, @subject_item = pagy @search.result, items: Settings.pagy
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <div class="col-md-8 col-md-offset-2">
    <%= f.label t ".name" %>
    <%= f.text_field :name, class: "form-control" %>
    <%= raw error_message(@subject, :name) %>
  </div>
  <div class="col-md-8 col-md-offset-2">
    <%= f.label t ".description" %>
    <%= f.text_field :description, class: "form-control" %>
    <%= raw error_message(@subject, :description) %>
  </div>
  <div class="col-md-3 col-md-offset-2">
    <%= f.label t ".question_number" %>
    <%= f.number_field :question_number, min: 0, step: 1, class: "form-control" %>
    <%= raw error_message(@subject, :question_number) %>
  </div>
  <div class="col-md-3">
    <%= f.label t ".score_pass" %>
    <%= f.number_field :score_pass, min: 0, step: 1, class: "form-control" %>
    <%= raw error_message(@subject, :score_pass) %>
  </div>
  <div class="col-md-2">
    <%= f.label t ".duration" %>
    <%= f.number_field :duration, min: 0, step: 1, class: "form-control" %>
    <%= raw error_message(@subject, :duration) %>
  </div>
  <div class="col-md-4 col-md-offset-4 mg-top-10">
    <%= f.submit yield(:button_text), class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/subjects/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save_changes") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <%= render "form" %>
</div>

app/views/admin/subjects/index.html.erb
<% provide(:title, t(".title")) %>
<h1><%= t ".title" %></h1>
<hr>
<div class="row">
  <div class="col-md-4 search-form">
    <%= search_form_for @search, url: admin_subjects_path, class: "form-inline" do |search| %>
      <%= search.search_field :name, class: "form-control" %>
      <%= button_tag(type: :submit, class: "btn btn-primary") do %>
        <i class="glyphicon glyphicon-search"></i>
      <% end %>
      <%= link_to new_admin_subject_path, :class=>"btn btn-success" do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    <% if @subject_item.any? %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col"><%= sort_link @search, t(".name") %></th>
            <th scope="col"><%= t ".description" %></th>
            <th scope="col"><%= t ".total_ques" %></th>
            <th scope="col"><%= t ".ques_num" %></th>
            <th scope="col"><%= t ".duration" %></th>
            <th scope="col"><%= t ".score_pass" %></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @subject_item.each do |subject| %>
            <tr>
              <td>
                <%=  link_to subject.name, admin_subject_questions_path(subject_id: subject.id) %>
              </td>
              <td><%= subject.description %></td>
              <td><%= subject.questions.count %></td>
              <td><%= subject.question_number %></td>
              <td><%= subject.duration %></td>
              <td><%= subject.score_pass %></td>
              <td>
                <%= link_to new_admin_subject_question_path(subject.id) do %>
                  <i class="fa fa-plus icon add-icon" aria-hidden="true"></i>
                <% end %>
                <%= link_to edit_admin_subject_path(subject.id)  do %>
                  <i class="fa fa-pencil-square icon edit-icon" aria-hidden="true"></i>
                <% end %>
                <%= link_to admin_subject_path(subject.id), method: :delete do %>
                  <i class="fa fa-trash icon delete-icon" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
    <% else %>
      <%= t ".no_subject" %>
    <% end %>
  </div>
</div>

app/views/admin/subjects/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <%= render "form" %>
</div>