config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "subjects#index"
    resources :static_pages, only: %i(index)
    resources :subjects, only: %i(index) do
      resources :exams, only: %i(show create update index)
    end
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users

    resources :relationships, only: %i(create)

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages, only: %i(index)
      resources :users, only: %i(index)
      resources :users do
        resources :exams, only: %i(index show)
      end
      resources :account_activations, only: %i(update)
      resources :subjects, only: %i(index new create edit update destroy)
      resources  :subjects do
        resources :questions
      end
      resources :questions do
        collection {post :import}
      end
      resources :answers
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  NESTED_ATTRS = %i(id content is_correct _destroy).freeze
  QUESTION_ATTRS = %i(question_content question_image subject_id question_type)
                   .push(answers_attributes: NESTED_ATTRS)
  MIN_ANSWER = 2

  after_update :clean_storage
  after_save :clean_storage
  after_destroy :clean_storage

  enum type: {single: 0, multiple: 1}

  belongs_to :subject
  counter_culture :subject
  has_many :answers, dependent: :destroy
  has_many :exam_relationships, class_name: Relationship.name,
                                dependent: :destroy

  has_many :exams, through: :exam_relationships, source: :exam

  has_one_attached :question_image

  accepts_nested_attributes_for :answers,
                                allow_destroy: true,
                                reject_if: proc{|att| att["content"].blank?}

  validates :question_content, :subject_id, :question_type, presence: true
  validates :question_type, inclusion: {in: Question.types.values}
  validate :check_single_choice, on: %i(create update)
  validates :question_image, {content_type: {
                                in: Settings.image_type,
                                message: "must be a valid image format"
                              },
                              size: {
                                less_than: 5.megabytes,
                                message: "should be less than 5MB"
                              }}
  scope :get_by_type, ->(type){where question_type: type}
  scope :get_by_id, ->(id){where id: id}
  scope :by_subject, ->(id){where subject_id: id if id.present?}

  class << self
    def types_i18n
      types.map do |key, value|
        [I18n.t("question.type.#{key}"), value]
      end
    end
  end

  def type_i18n type_id
    type = Question.types.keys[type_id]
    I18n.t("question.type.#{type}")
  end

  class << self
    def import file
      spreadsheet = open_spreadsheet(file)
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        Question.create! handle_data row
      end
    end

    def handle_data row
      row[:subject_id] = (Subject.find_by name: row["subject"]).id
      row[:question_content] = row["question content"].strip
      row[:question_type] = handle_type row["question type"]
      row[:answers_attributes] = handel_excel row["answers attributes"].strip
      row.delete "subject"
      row.delete "question type"
      row.delete "question content"
      row.delete "answers attributes"
      row
    end

    def handle_type question_type
      case question_type
      when Question.types[:single]
        Question.types[:single]
      when Question.types[:multiple]
        Question.types[:multiple]
      end
    end

    def open_spreadsheet file
      case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    rescue StandardRecord
      Rails.logger = Logger.new "Unknown file type"
    end

    protected

    def handel_excel row
      row.split(",").map do |attribute|
        attribute_hash = Hash.new
        arr_option = attribute.split(":")
        attribute_hash[:content] = arr_option[0]
        attribute_hash[:is_correct] = arr_option[1]
        attribute_hash
      end
    end
  end

  def question_image_path
    ActiveStorage::Blob.service.path_for(question_image.key)
  end

  private
  def check_valid_question
    return true if answers.size >= MIN_ANSWER

    errors.add(:question_content, :not_enough_answer)
  end

  def check_single_choice
    check_valid_question
    correct_count = answers.map(&:is_correct).count(true)
    return true if correct_count.positive? &&
                   question_type == Question.types[:multiple]
    return true if correct_count == Settings.single_correct_answer &&
                   question_type == Question.types[:single]

    errors.add(:answers, :not_valid_correct_answer_number)
  end

  def clean_storage
    Dir.glob(Rails.root.join("storage/**/*").to_s)
       .sort_by(&:length).reverse.each do |x|
      Dir.rmdir(x) if File.directory?(x) && Dir.empty?(x)
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_question, except: %i(index new create import)

  def index
    store_location
    questions = Question.by_subject(params[:subject_id])
    @search = questions.ransack question_content_cont:
                                params[:q] ? params[:q][:question_content] : ""
    @search.sorts = params.dig(:q, :s) || "id asc"
    handle_param
  end

  def new
    @question_index = 1
    @question = Question.new
    @subject = Subject.pluck :name, :id
    @question.answers.build
    @question.answers.build
  end

  def create
    @question = Question.new question_params
    # @question.question_image.attach(params[:question][:question_image])
    @subject = Subject.pluck :name, :id
    if @question.save
      flash[:success] = t ".created"
      redirect_back_or admin_questions_path
    else
      flash[:error] = t ".create_failed"
      render :new
    end
  end

  def edit
    @question = Question.find_by id: params[:id]
    @subject = Subject.pluck :name, :id
    @type = Question.types
  end

  def update
    @question = Question.find_by id: params[:id]
    @question.question_image.purge unless params[:question][:is_attach_image]
    @subject_id = @question.subject_id
    if @question.update question_params
      flash[:success] = "update_success"
      redirect_back_or admin_questions_path
    else
      flash[:danger] = "update_false"
      render :edit
    end
  end

  def import
    arr_file = Settings.import
    if params[:file].blank?
      flash[:danger] = "Fields cannot be blank!"
    elsif arr_file.include? params[:file].original_filename.split(".").last
      import_file
    else
      flash[:danger] = "Not format"
    end
    redirect_to admin_questions_path
  end

  def destroy
    if @question.includes(answers: :exam_relationships).destroy(params[:id])
      flash[:success] = "Question deleted"
    else
      flash[:danger] =  "Questiom delete failed"
    end
    redirect_back_or admin_questions_path
  end

  private
  def question_params
    params.require(:question).permit Question::QUESTION_ATTRS
  end

  def find_question
    @question = Question.get_by_id(params[:id])
    return if @question.present?

    flash[:danger] = t "not_found"
    redirect_to admin_questions_path
  end

  def handle_param
    if params[:subject_id]
      sub_path = new_admin_subject_question_path(params[:subject_id])
      search_path = admin_subject_questions_path(params[:subject_id])
    end
    @pagy, @question_item = pagy @search.result, items: Settings.pagy
    @search_path = params[:subject_id] ? search_path : admin_questions_path
    @path = params[:subject_id] ? sub_path : new_admin_question_path
  end

  def import_file
    if Question.import(params[:file])
      flash[:success] = "Question imported."
    else
      flash[:danger] = "Question import failed"
    end
  end
end

app/views/admin/questions/_answer_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <div class="col-md-1 answer-content">
      <%= f.label :content, t(".answer_content"), class: "control-label required" %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :content, class: "form-control answer-input", required: true %>
    </div>
    <div class="col-md-2">
      <%= f.label :is_correct, t(".is_correct"), class: "control-label" %>
      <%= f.check_box :is_correct, class: "answer-input answer-check-box check-box", onclick:"check_question_type(this)" %>
    </div>
    <div class="col-md-1 col-md-offset-3">
      <%= link_to_remove_association t(".remove"), f, class: "btn btn-danger btn-xs" %>
    </div>
  </div>
  <hr>
</div>

app/views/admin/questions/_form.html.erb
<%= form_for @question, url: url, html: {class: "form-horizontal"} do |form| %>
  <div class="form-group">
    <div class="col-md-5">
      <%= form.label :question_content, t(".ques_content") %>
      <%= form.text_area :question_content, class: "form-control custom-textarea-question-content", required: true %>
      <div class="input-file">
        <%= form.file_field :question_image, accept:"image/jpeg,image/gif,image/png"%>
        <label for="question_question_image">Attach images to question (PNG, JPG)</label>
        <% if @question.question_image.attached? %>
          <%= @question.question_image_path %>
          <ul class="preview" style="display: flex;">
            <%= form.hidden_field :is_attach_image, value: true %>
            <li>
              <i class="fa fa-close preview-close"></i>
              <%= image_tag @question.question_image, width: "50", height: "50", id: "image-attach" %>
            </li>
          </ul>
        <% else %>
          <ul class="preview">
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-md-3 col-md-offset-1">
      <%= form.label :subject, t(".subject") %>
      <%= form.select "subject_id", options_for_select(@subject, selected: @question.subject_id || params[:subject_id]), {}, {class: "form-control custom-select" }%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= form.label :question_type, t(".type") %>
      <%= form.select :question_type, options_for_select(Question.types_i18n, selected: @question.question_type), {}, {class: "form-control custom-select", onchange: "clearChecked()"} %>
    </div>
  </div>
  <hr>
  <div>
    <div id="answers">
      <%= form.fields_for :answers, html: { class: "form-horizontal answerForm" } do |field| %>
        <%= render "answer_fields", f: field %>
        <%= raw error_message(@question, :answers) %>
      <% end %>
      <div class="links">
        <%= link_to_add_association t(".add"), form, :answers, partial: "answer_fields", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="actions save-question">
    <%= form.submit yield(:button_text), class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save_changes") %>
<h1><%= t ".title" %></h1>
<%= render "form", url: admin_question_path(@question.id) %>
<%= javascript_pack_tag "question", "data-turbolinks-track": "reload" %>

app/views/admin/questions/index.html.erb
<% provide(:title, "All question") %>
<h1>All question</h1>
<div id="modal-image">
  <span class="close-modal">&times;</span>
  <img class="modal-content" id="image-modal">
</div>
<hr>
<div class="row">
  <div class="col-md-4 search-form">
    <%= search_form_for @search,url: @search_path, class: "form-inline" do |search| %>
      <%= search.search_field :question_content, class: "form-control" %>
      <%= button_tag(type: :submit, class: "btn btn-primary") do %>
        <i class="glyphicon glyphicon-search"></i>
      <% end %>
    <% end %>
    <%= link_to @path, :class=>"btn btn-success" do %>
      <i class="fa fa-plus" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag import_admin_questions_path, multipart: true, class: "import-button" do %>
      <%= file_field_tag :file %>
      <%= button_tag(type: :submit_tag, class: "btn btn-default") do %>
        <i class="glyphicon glyphicon-import"></i>
      <% end %>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    <% if @question_item.any? %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col"><%= sort_link @search, :question_content %></th>
            <th scope="col">Question type</th>
            <th scope="col">Subject</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @question_item.includes([:subject]).each do |question| %>
            <tr>
              <td>
                <%= question.question_content %> <br/>
                <%= image_tag question.question_image, class: "td-question-image", :onclick => "createImageModal(this)" if question.question_image.attached? %>
              </td>
              <td><%= question.type_i18n question.question_type %></td>
              <td><%= question.subject.name %></td>
              <td>
                <%= link_to edit_admin_question_path(question.id)  do %>
                  <i class="fa fa-pencil-square icon edit-icon" aria-hidden="true"></i>
                <% end %>
                <%= link_to admin_question_path(question.id),
                            data: {confirm: "Are you sure to delete this question?"}, method: :delete do %>
                  <i class="fa fa-trash icon delete-icon" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
    <% else %>
      <%= t ".no_subject" %>
    <% end %>
  </div>
</div>
<%= javascript_pack_tag "question", "data-turbolinks-track": "reload" %>

app/views/admin/questions/new.html.erb
<h1><%= t ".title" %></h1>
<% provide :button_text, t(".submit") %>
<div class="row">
  <%= render "form", url: admin_questions_path %>
</div>
<%= javascript_pack_tag "question", "data-turbolinks-track": "reload" %>