config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "subjects#index"
    resources :static_pages, only: %i(index)
    resources :subjects, only: %i(index) do
      resources :exams, only: %i(show create update index)
    end
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users

    resources :relationships, only: %i(create)

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages, only: %i(index)
      resources :users, only: %i(index)
      resources :users do
        resources :exams, only: %i(index show)
      end
      resources :account_activations, only: %i(update)
      resources :subjects, only: %i(index new create edit update destroy)
      resources  :subjects do
        resources :questions
      end
      resources :questions do
        collection {post :import}
      end
      resources :answers
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exams, dependent: :destroy

  USER_ATTRS = %i(name email password password_confirmation remember_me).freeze
  enum role_id: {user: 0, admin: 1}
  before_save :downcase_email

  validates :email, presence: true,
                    length: {minium: Settings.min_length,
                             maximum: Settings.max_length},
                    format: {with: Settings.email_regex},
                    uniqueness: {case_sensitive: false}

  validates :name, presence: true,
                   length: {minium: Settings.min_length,
                            maximum: Settings.max_length}

  validates :password, presence: true,
                       length: {minimum: Settings.password_min_length},
                       allow_nil: true

  def activate_or_inactive
    update activated: !activated, activated_at: Time.zone.now
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @search = User.ransack email_cont: params[:q] ? params[:q][:email] : ""
    @pagy, @user_item = pagy @search.result.user, items: Settings.pagy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: %i(new create)
  before_action :logged_in_user, :correct_user, only: %i(edit update)

  def show
    return if @user

    flash.now[:error] = t "not_found"
    redirect_to root_path
  end

  def new
    @user = User.new
    return if @user

    flash.now[:error] = t "not_found"
    redirect_to root_path
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "success_signup"
      redirect_to root_path
    else
      flash.now[:error] = t "fail_signup"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t ".update_success"
      redirect_to root_path
    else
      flash.now[:error] = t ".update_false"
      render :edit
    end
  end
end

app/views/admin/users/index.html.erb
<% provide(:title, t(".title" )) %>
<h1><%= t ".heading" %></h1>
<hr>
<div class="row">
  <div class="col-md-4 search-form">
    <%= search_form_for @search, url: admin_users_path, class: "form-inline" do |search| %>
      <%= search.search_field :email, class: "form-control" %>
      <%= button_tag(type: :submit, class: "btn btn-primary") do %>
        <i class="glyphicon glyphicon-search"></i>
      <% end %>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    <% if @user_item.any? %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col"><%= t ".name" %></th>
            <th scope="col"><%= t ".email" %></th>
            <th scope="col"><%= t ".attended" %></th>
            <th scope="col"><%= t ".passed" %></th>
            <th scope="col"><%= t ".action" %></th>
          </tr>
        </thead>
        <tbody>
          <% @user_item.each do |user| %>
            <tr class="<%= status_account(user) %>">
              <td><%= user_link user %></td>
              <td><%= user.email %></td>
              <td><%= count_attended_subject user.exams %></td>
              <td><%= count_attended_subject user.exams %></td>
              <td>
                <%= link_to admin_account_activation_path(user.id), method: :patch do %>
                  <i class="<%= icon_active_or_inactive(user) %>" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
    <% else %>
      <%= t ".no_user" %>
    <% end %>
  </div>
</div>