config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "subjects#index"
    resources :static_pages, only: %i(index)
    resources :subjects, only: %i(index) do
      resources :exams, only: %i(show create update index)
    end
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users

    resources :relationships, only: %i(create)

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages, only: %i(index)
      resources :users, only: %i(index)
      resources :users do
        resources :exams, only: %i(index show)
      end
      resources :account_activations, only: %i(update)
      resources :subjects, only: %i(index new create edit update destroy)
      resources  :subjects do
        resources :questions
      end
      resources :questions do
        collection {post :import}
      end
      resources :answers
    end
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("maxe"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t(".languages") %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".vi"), locale:"vi" %></li>
            <li class="divider"></li>
            <li><%= link_to t(".en"), locale:"en" %></li>
          </ul>
        </li>
        <% if !user_signed_in? %>
          <li><%= link_to t(".subjects"), static_pages_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".account"), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("maxe_admin"), admin_root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t(".languages") %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".vi"), locale:"vi" %></li>
            <li class="divider"></li>
            <li><%= link_to t(".en"), locale:"en" %></li>
          </ul>
        </li>
        <li><%= link_to t(".users"), admin_users_path %></li>
        <li><%= link_to t(".subjects"), admin_subjects_path %></li>
        <li><%= link_to t(".questions"), admin_questions_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".account"), edit_user_registration_path %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= toastr_flash %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header_admin" %>
    <div class="container">
      <%= toastr_flash %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>